name: Deploy Documentation

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:  # 手動実行も可能

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      # リポジトリのチェックアウト
      - name: Checkout
        uses: actions/checkout@v4
      
      # Juliaのセットアップ
      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'  # または '1' で最新安定版
      
      # Juliaパッケージのキャッシュ（Plotsのコンパイル済みファイルも含む）
      - name: Cache Julia packages
        uses: julia-actions/cache@v2
        with:
          cache-name: julia-cache-plots-v1
          cache-compiled: true  # コンパイル済みファイルもキャッシュ
      
      # Documenter.jlのインストール
      - name: Install dependencies
        run: |
          julia -e '
            using Pkg
            Pkg.activate("docs")
            Pkg.instantiate()
          '
      
      # ドキュメントのビルド
      - name: Build documentation
        env:
          CI: true  # prettyurlsを有効にするための環境変数
        run: |
          cd docs
          julia make_deploy.jl
      
      # GitHub Pages用の設定
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      # ビルド結果をアーティファクトとしてアップロード
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/build'
      
      # GitHub Pagesへデプロイ
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4